--- #YAML:1.0
name:                IO-Compress-Lzop
version:             2.011
abstract:            Write lzop files/buffers
license:             perl
author:              
    - Paul Marquess <pmqs@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Compress::LZO:                 0
    IO::Compress::Base:            2.011
    IO::Uncompress::Base:          2.011
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
