--- #YAML:1.0
name:               IO-Compress-Lzop
version:            2.017
abstract:           Write lzop files/buffers
author:
    - Paul Marquess <pmqs@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Compress::LZO:        0
    IO::Compress::Base:   2.017
    IO::Uncompress::Base:  2.017
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
